name: Android CI

on:
  push:
    branches: [ "master" , "develop"]
  pull_request:
    branches: [ "master", "develop"]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build

    - name: Run lint
      run: ./gradlew lintDebug

    - name: Upload html test report
      uses: actions/upload-artifact@v2
      with:
        name: lint.html
        path: app/build/reports/lint-results-debug.html

  unit-test:
      name: Perform Unit Testing
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - name: set up JDK 17
          uses: actions/setup-java@v3
          with:
            java-version: '17'
            distribution: 'temurin'
            cache: gradle
        - name: Run tests
          run: ./gradlew test

  apk:
    name: Build Release signed APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'

      - name: Build Release APK
        run: ./gradlew assembleRelease

      - name: Sign APK
        uses: r0adkll/sign-android-release@v1
        id: sign_app
        with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.KEYSTORE_NAME }}
          alias: ${{ secrets.KEY_ALIAS }}
          keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
        env:
          BUILD_TOOLS_VERSION: "34.0.0"

      - name: Create service_account.json
        run: echo '${{ secrets.SERVICE_ACCOUNT_JSON }}' > service_account.json


  upload-app:
        name: "Upload App to BrowserStack"
        runs-on: ubuntu-latest
        steps:
          - name: Check out Git repository
            uses: actions/checkout@v2

          - name: Upload Android App
            id: android_app_upload
            uses: fjogeleit/http-request-action@master
            with:
              url: https://api-cloud.browserstack.com/app-automate/upload
              method: POST
              username: ${{ env.BSTACK_USER }}
              password: ${{ env.BSTACK_ACCESS_KEY }}
              data: '{ "custom_id": "AndroidApp" }'
              files: '{ "file": "${{ github.workspace }}/app/build/outputs/release/*.aab" }'

     # - name: Deploy to Alpha
        #  uses: r0adkll/upload-google-play@v1
          #with:
          #serviceAccountJson: service_account.json
          #packageName: com.lib.gitactioncicd
          #releaseFiles: app/build/outputs/bundle/release/app-release.aab
          #track: alpha
        #status: completed


